## Append samples of your project ##
resources:
- infrastructure_v1beta1_harvestermachine.yaml
- infrastructure_v1beta1_harvestercluster.yaml
- infrastructure_v1beta1_harvestermachinetemplate.yaml
- infrastructure_v1beta1_harvesterclustertemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
