apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caphv.fullname" . }}
  namespace: {{ include "caphv.namespace" . }}
  labels:
    {{- include "caphv.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "caphv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "caphv.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --health-probe-bind-address={{ .Values.healthProbe.bindAddress }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            {{- if .Values.leaderElect }}
            - --leader-elect
            {{- end }}
            {{- if .Values.webhooks.enabled }}
            - --enable-webhooks
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          ports:
            - containerPort: 8081
              name: healthz
              protocol: TCP
            {{- if .Values.webhooks.enabled }}
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
          {{- if .Values.webhooks.enabled }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          {{- end }}
      {{- if .Values.webhooks.enabled }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.webhooks.certSecretName }}
      {{- end }}
