name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      - name: Install dependencies
        run: zypper -n install git tar gzip curl gawk go nodejs-default

      - name: Clone the code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Fix git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11.1
          args: --timeout=5m
          skip-cache: true
