name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      - name: Install dependencies
        run: zypper -n install git tar gzip curl gawk go

      - name: Clone the code
        uses: actions/checkout@v4

      - name: Fix git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | bash -s -- -b /usr/local/bin v2.11.1

      - name: Run linter
        run: golangci-lint run --timeout 5m ./...
