name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      - name: Install dependencies
        run: zypper -n install git tar gzip curl

      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
