name: test

on:
  push:
    branches:
    - main
    - harvester-*
  pull_request:
    branches:
    - main
    - harvester-*

permissions:
  contents: read

jobs:
  unit-test:
    name: unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
    - name: Install dependencies
      run: zypper -n install git tar gzip make gcc go

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Fix git safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Run unit tests
      run: make test

    - name: Build
      run: make build
