name: test

on:
  push:
    branches:
    - main
    - harvester-*
  pull_request:
    branches:
    - main
    - harvester-*

jobs:
  unit-test:
    name: unit-tests
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest
    defaults:
      run:
        shell: /usr/bin/bash -e {0}
    steps:
    - name: Install dependencies
      run: zypper -n install git tar gzip make gcc

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Run unit tests
      run: make test

    - name: Build
      run: make build
